version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Test
          command: |
            set +e

            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion            

            export NODE_VERSION="v12.18.3"

            nvm install "$NODE_VERSION"
            nvm use "$NODE_VERSION"
            nvm alias default "$NODE_VERSION"

            node --version
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            ./.cicd/test.sh
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Integration Test
#          command: |
#            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#            chmod +x ~/docker-compose
#            sudo mv ~/docker-compose /usr/local/bin/docker-compose
#            sudo ls -la
#            docker create --network env_default --name tests
#            ./.cicd/integration-test.sh
