DROP TABLE IF EXISTS "QUERIES";
CREATE TABLE IF NOT EXISTS "QUERIES"
(
    "UUID" UUID NOT NULL,
    "VALUE" VARCHAR NOT NULL,
    "ID" BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE UNIQUE INDEX IF NOT EXISTS "UUID_INDEX" ON "QUERIES" ("UUID");