version: '3.7'

services:

  # S C A L C I T E
  scalcite-example-backend:
    container_name: scalcite-example-backend
    image: mvillafuertem/scalcite-example-backend:0.1.1
    restart: always
    ports:
      - 8080:8080
      - 1099:1099
    environment:
      - JAVA_OPTS=-Xmx512m -Xms128m -XX:MaxMetaspaceSize=512m
    depends_on:
      - postgres
    external_links:
      - "postgres:postgres.local"
      - "apm:apm.local"

  # I N F R A S T R U C T U R E
  postgres:
    container_name: postgres
    hostname: "postgres.local"
    image: postgres:9.6.17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  apm:
    container_name: apm
    hostname: "apm.local"
    image: docker.elastic.co/apm/apm-server:7.6.2
    volumes:
      - ./apm-server.yml:/etc/apm-server.yml
    ports:
      - 8200:8200
    restart: always
    depends_on:
      - kibana
      - elasticsearch
    external_links:
      - "kibana:kibana.local"
      - "elasticsearch:elasticsearch.local"

  kibana:
    container_name: kibana
    hostname: "kibana.local"
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    restart: always
    depends_on:
      - elasticsearch
    external_links:
      - "elasticsearch:elasticsearch.local"

  elasticsearch:
    container_name: elasticsearch
    hostname: "elasticsearch.local"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    restart: always

  adminer:
    container_name: adminer
    image: adminer:4.7.6
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - postgres
    external_links:
      - "postgres:postgres.local"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.20
    restart: always
    ports:
      - 9002:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: rootpassword
    depends_on:
      - postgres
    external_links:
      - "postgres:postgres.local"
