version: '3.7'

services:

  # S C A L C I T E
  scalcite-example-backend:
    image: mvillafuertem/scalcite-example-backend:0.1.1
    restart: always
    ports:
      - 8080:8080
      - 1099:1099
    environment:
      - JAVA_OPTS=-Xmx512m -Xms128m -XX:MaxMetaspaceSize=512m
    depends_on:
      - postgres

  # I N F R A S T R U C T U R E
  postgres:
    image: postgres:9.6.17
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - 9002:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ""
#      PGADMIN_DEFAULT_PASSWORD: ""
    depends_on:
      - postgres

#networks:
#  postgres-compose-network:
#    driver: bridge
